unit TestudmMain;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Classes, DB, SysUtils, ADODB, udmMain;
type
  // Test methods for class TdmMain
  
  TestTdmMain = class(TTestCase)
  strict private
    FdmMain: TdmMain;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TeststkConnBeforeConnect;
    procedure TestinfoConnBeforeConnect;
    procedure TeststkConnConnectComplete;
    procedure TestinfoConnConnectComplete;
  end;

implementation

procedure TestTdmMain.SetUp;
begin
  FdmMain := TdmMain.Create;
end;

procedure TestTdmMain.TearDown;
begin
  FdmMain.Free;
  FdmMain := nil;
end;

procedure TestTdmMain.TeststkConnBeforeConnect;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FdmMain.stkConnBeforeConnect(Sender);
  // TODO: Validate method results
end;

procedure TestTdmMain.TestinfoConnBeforeConnect;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FdmMain.infoConnBeforeConnect(Sender);
  // TODO: Validate method results
end;

procedure TestTdmMain.TeststkConnConnectComplete;
var
  EventStatus: TEventStatus;
  Error: Error;
  Connection: TADOConnection;
begin
  // TODO: Setup method call parameters
  FdmMain.stkConnConnectComplete(Connection, Error, EventStatus);
  // TODO: Validate method results
end;

procedure TestTdmMain.TestinfoConnConnectComplete;
var
  EventStatus: TEventStatus;
  Error: Error;
  Connection: TADOConnection;
begin
  // TODO: Setup method call parameters
  FdmMain.infoConnConnectComplete(Connection, Error, EventStatus);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTdmMain.Suite);
end.

