unit TestExamCommonsCompress;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework,testextensions;

type
    TTestSetupForCommonCompress=class(TTestSetup)
  protected
    procedure SetUp; override;
    procedure TearDown; override;
  end;
   // Test methods for class TfrmInProcess
   
   TTestCaseForEaxmCommonsCompress = class(TTestCase)
   strict private
  private


   public
      procedure SetUp; override;
      procedure TearDown; override;
   published
      procedure TestFileCompression;
      procedure TestDirectoryCompression;
      procedure TestDirectoryDeCompression;
   end;
var
   ///   测试数据源路径，  此目录为只用于读、不用于写
   TestDataSourcePath :string;
   ///测试数据目标路径，此目录可读可写
   TestDataDestPath:string;
implementation
uses Classes, SysUtils,compress,Commons, Forms;

procedure TTestCaseForEaxmCommonsCompress.SetUp;
begin
end;

procedure TTestCaseForEaxmCommonsCompress.TearDown;
begin

end;

/// <summary>
///  将 TestDataSourcePath 中文件  compressTestSource.dat 压缩保存到compressTestTarget.dat
///  条件：compressTestSource.dat文件必须存在
/// </summary>
procedure TTestCaseForEaxmCommonsCompress.TestFileCompression;
var
   memStream: TMemoryStream;
begin
   memStream:=TMemoryStream.Create;
   try
     FileCompression(TestDataSourcePath+'\TestCompressSource.dat',memStream);
     memStream.SaveToFile(TestDataDestPath+'\'+'TestCompressTarget.dat');
   finally
     memStream.Free;
   end;
end;

/// <summary>
///  将 TestExamineeFolderPath 中文件夹 11111100101 打包压缩保存到 TestDirCompress.dat
///  条件：11111100101文件夹必须存在
/// </summary>
procedure TTestCaseForEaxmCommonsCompress.TestDirectoryCompression;
var
   memStream: TMemoryStream;
begin
   DirectoryCompression(TestDataSourcePath+'\TestCompressDirSource',memStream);
   try
     memStream.SaveToFile(TestDataDestPath+'\'+'TestDirCompress.dat');
   finally
     memStream.Free;
   end;
end;

/// <summary>
///  将 TestExamineeFolderPath 中文件 TestDirCompress.dat 解压还原生成 11111100101 文件夹
///  条件：TestDirCompress.dat 文件必须存在  此文件由 TestDirectoryCompression 测试用例来生成
/// </summary>
procedure TTestCaseForEaxmCommonsCompress.TestDirectoryDeCompression;
var
   memStream: TMemoryStream;
begin
   memStream:= TMemoryStream.Create;
   memStream.LoadFromFile(TestDataDestPath+'\'+'TestDirCompress.dat');
   memStream.Position := 2; //test not start 0;
   if DirectoryExists(TestDataDestPath+'\'+'DirDecompress') then begin
      deleteDir(TestDataDestPath+'\'+'DirDecompress');
   end;
   CreateDir(TestDataDestPath+'\'+'DirDecompress');
   DirectoryDecompression(TestDataDestPath+'\'+'DirDecompress',memStream);
end;

{ TTestSetupForTcpClient }



{ TTestSetupForCommonFileDirCompress }

procedure TTestSetupForCommonCompress.SetUp;
var
   appPath:string;
begin
  inherited;
   appPath := ExtractFilePath(Application.ExeName);
   TestDataSourcePath:= appPath+'testDataSource';
   TestDataDestPath := appPath+'testDataDest';
   //重新生成测试目标目录
   if DirectoryExists(TestDataDestPath) then begin
      deleteDir(TestDataDestPath);
   end;
   CreateDir(TestDataDestPath);
end;

procedure TTestSetupForCommonCompress.TearDown;
begin
  inherited;

end;

initialization
  // Register any test cases with the test runner
   // Register any test cases with the test runner
  RegisterTest(TTestSetupForCommonCompress.Create(TTestCaseForEaxmCommonsCompress.Suite));
  //RegisterTest(TTestSetupForTcpClient.Create( TestTExamServerCommand.Suite));
  //RegisterTest(TTestCaseForEaxmCommonsCompress.Suite);
end.

